apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    k8s-app: fluent-bit
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE <deployment 이름>.conf
  
  <deployment 이름>.conf: |
    [INPUT]
        Name                  tail
        Tag                   <deployment 이름>.*
        Path                  /var/log/containers/<deployment 이름>*
        multiline.parser      docker, cri
        DB                    /var/log/flb_kube.db
        Mem_Buf_Limit         5MB
        Skip_Long_Lines       On
        Refresh_Interval      10

    [FILTER]
        Name                  kubernetes
        Match                 <deployment 이름>.*
        Merge_Log             On
        Merge_Log_Key         log_processed
        K8S-Logging.Parser    On
        K8S-Logging.Exclude   On

    [OUTPUT]
        Name                  opensearch
        Match                 <deployment 이름>.*
        Host                  ${OPENSEARCH_ENDPOINT}
        Port                  443
        HTTP_User             ${OPENSEARCH_USER}
        HTTP_Passwd           ${OPENSEARCH_PASSWORD}
        tls                   On
        tls.verify            Off
        Logstash_Format       On
        Logstash_Prefix       <로그 이름>
        Logstash_DateFormat   %Y.%m.%d
        Replace_Dots          On
        Suppress_Type_Name    On

  parsers.conf: |
    [PARSER]
        Name                syslog
        Format              regex
        Regex               ^(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key            time
        Time_Format         %b %d %H:%M:%S

    [PARSER]
        Name                container_firstline
        Format              regex
        Regex               (?<log>(?<="log":")\S(?!\.).*?)(?<!\\)".*(?<stream>(?<="stream":").*?)".*(?<time>\d{4}-\d{1,2}-\d{1,2}T\d{2}:\d{2}:\d{2}\.\w*).*(?=})
        Time_Key            time
        Time_Format         %Y-%m-%dT%H:%M:%S.%LZ
