apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit
  namespace: <네임스페이스>
  labels:
    k8s-app: fluent-bit-logging
    version: v1
spec:
  replicas: 2  # 원하는 복제본 수
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
  template:
    metadata:
      annotations:
        prometheus.io/path: /api/v1/metrics/prometheus
        prometheus.io/port: "2020"
        prometheus.io/scrape: "true"
      labels:
        k8s-app: fluent-bit-logging
        version: v1
    spec:
      containers:
      - env:
        - name: AWS_REGION
          value: 리전
        - name: <환경변수>
          value: <환경변수>   
          
        name: fluent-bit-cnt
        image: amazon/aws-for-fluent-bit:2.32.2
        imagePullPolicy: Always
        ports:
        - containerPort: 2020
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /fluent-bit/etc/
          name: fluent-bit-config
      serviceAccountName: fluent-bit
      terminationGracePeriodSeconds: 10
      volumes:
      - hostPath:
          path: /var/log
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
        name: varlibdockercontainers
      - configMap:
          name: fluent-bit-config
        name: fluent-bit-config     
