apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dev-externalsecret
  namespace: wsi
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: dev-secretstore
    kind: SecretStore
  target:
    name: app-secret
    creationPolicy: Owner
  data:
  - secretKey: MYSQL_USER
    remoteRef:
      key: <Secret Manager 보안 암호 이름>
      property: username
  - secretKey: MYSQL_PASSWORD
    remoteRef:
      key: <Secret Manager 보안 암호 이름>
      property: password
