apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: <Role 이름>
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: <RoleBinding 이름>
roleRef:
  kind: ClusterRole
  name: <Role 이름>
  apiGroup: rbac.authorization.k8s.io
  
subjects:
- kind: Group
  name: <Aws Auth Group name>
  apiGroup: rbac.authorization.k8s.io
